version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8085:8085
     - 50001:50001
    container_name: jenkinss
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./jenkinss_home:/var/jenkinss_home
